on: [push, pull_request]
name: build
jobs:
  tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
        include:
          - clickhouse-version: 22.5.1.2079
            clickhouse-org: clickhouse
          - clickhouse-version: 23.8.4.69
            clickhouse-org: clickhouse
    services:
      clickhouse-server:
        image: ${{ matrix.clickhouse-org }}/clickhouse-server:${{ matrix.clickhouse-version }}
        ports:
          - 8123:8123
          - 9000:9000

    name: ${{ matrix.python-version }} CH=${{ matrix.clickhouse-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Show UV version
        run: uv --version

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Activate venv
        run: source $VENV || source .venv/bin/activate

      - name: Run checks
        run: make check